name: 'Create pre release Version'

on:
  push:
    branches:
      - 'develop'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Bump-Version:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip')"
    steps:
        - name: checkout code
          uses: actions/checkout@v2
        
        - name: Git Email
          run: git config --global user.email 'ruandv@gmail.com'
          
        - name: Git UserName
          run: git config --global user.name 'ruandv'
        
        # Runs a single command using the runners shell
        - name: install packages
          run: yarn install

        # Runs a single command using the runners shell
        - name: Update version
          run: yarn run release:dev

        # Runs a single command using the runners shell
        - name: push new version
          run: |
            git config --global user.name 'Ruan'
            git config --global user.email 'ruandv@gmail.com'
            git push origin develop