name: 'Create a Release Version'

on:
  pull_request:
    branches: [master]
    types: [closed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Bump-Version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: Git Email
        run: git config --global user.email 'ruandv@gmail.com'
        
      - name: Git UserName
        run: git config --global user.name 'ruandv'
        
    # Runs a single command using the runners shell
      - name: install packages
        run: yarn install

      # Runs a single command using the runners shell
      - name: Update version
        run: yarn run release

      # Runs a single command using the runners shell
      - name: push new version
        run: |
          git config --global user.name 'Ruan'
          git config --global user.email 'ruandv@gmail.com'
          git push origin master
  merge-master-back-to-dev:
    needs: Bump-Version
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: develop
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git pull
          git checkout master
          git pull
          git checkout -
          git merge --no-ff master -m "chore: Auto-merge master back to dev"
          git push origin/develop